_behat_launcher_project_list:
    path: /
    defaults: { _controller: "AlexBehatLauncherBundle:Project:list" }

_behat_launcher_project_show:
    path: /project/{project}
    defaults: { _controller: "AlexBehatLauncherBundle:Project:show" }

_behat_launcher_run_list:
    path: /run
    defaults: { _controller: "AlexBehatLauncherBundle:Run:list" }

_behat_launcher_run_create:
    path: /project/{project}/create-run
    defaults: { _controller: "AlexBehatLauncherBundle:Run:create" }

_behat_launcher_run_show:
    path: /run/{id}
    requirements: { id: \d+ }
    defaults: { _controller: "AlexBehatLauncherBundle:Run:show" }
