# Configuration for stage1.io
build:
    - "composer install --no-interaction --ansi --no-progress"
    - "cp config.php.dist config.php"
    - "php behat-launcher init-db"
    - "php behat-launcher run &"
writable:
    - app/cache
    - app/data
